choco install 7zip-zstd -y
choco install asar7z -y
choco install smart7z -y
choco install lzip7z -y
choco install thumbs7z -y
choco install grit7z -y
choco install exfat7z -y
choco install modern7z -y
choco install wavpack7z -y
choco install forensic7z -y
choco install iso7z -y
choco install edecoder -y
choco install mfilter -y