choco install vb5runtime -y
choco install dotnet-runtime -y
choco install dotnetcore-runtime -y
choco install dotnet-5.0-runtime -y
choco install dotnet-6.0-runtime -y
choco install jre8 -y
choco install adobeair -y
choco install vcredist-all -y
choco install msvisualcplusplus2012-redist -y
choco install msvisualcplusplus2013-redist -y
choco install vcredist2012 -y
choco install vcredist2008 -y
choco install vcredist140 -y
choco install ext2fsd -y
choco install xna -y
choco install xna31 -y
choco install msxml6.sp1 -y
choco install msxml4.sp3 -y
choco install vlc -y
choco install eartrumpet -y
choco install modernflyouts -y
exit
